name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}-devcontainer

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Load Airflow connections
        env:
          AIRFLOW_CONNECTIONS: ${{ secrets.AIRFLOW_CONNECTIONS }}
        run: |
          echo "$AIRFLOW_CONNECTIONS" > connections.yml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.IMAGE_NAME }}
          push: always

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Devcontainer image
          imageName: ${{ env.IMAGE_NAME }}
          # Run setup, validation and tests in dev container
          runCmd: |
            # Run setup first
            script/setup
            # Import airflow connections
            airflow connections import connections.yml
            # Run pre-commit checks
            pre-commit run --all-files --verbose --show-diff-on-failure
            # Run tests (which now have access to connections)
            script/test

      - name: Cleanup Files
        run: |
          rm connections.yml
